sonar.organization=sonar-workshop-1
sonar.projectKey=workshop-python
sonar.projectName=SonarQube Cloud Python Workshop

sonar.sources=.
sonar.exclusions=**/migrations/**,**/*.sqlite3,.venv/**

sonar.python.version=3.10,3.11,3.12
sonar.python.coverage.reportPaths=coverage.xml

sonar.sourceEncoding=UTF-8
